select * from family_status;
	
ALTER TABLE family_status
ADD COLUMN MARRIED_RATIO numeric;

ALTER TABLE family_status
ADD COLUMN FEMALE_HOH_RATIO numeric;

ALTER TABLE family_status
ADD COLUMN MALE_HOH_RATIO numeric;

ALTER TABLE family_status
ADD COLUMN NON_FAMILY_RATIO numeric;

	
DELETE FROM family_status WHERE "U18 POPULATION IN TOTAL" = 0;

UPDATE family_status set married_ratio = ("U18 POPULATION MARRIED COUPLES" * 1.0 / "U18 POPULATION IN TOTAL");
UPDATE family_status set FEMALE_HOH_RATIO = ("U18 POPULATION FEMALE HOUSEHOLD" * 1.0 / "U18 POPULATION IN TOTAL");
UPDATE family_status set MALE_HOH_RATIO = ("U18 POPULATION MALE HOUSEHOLD" * 1.0 / "U18 POPULATION IN TOTAL");
UPDATE family_status set NON_FAMILY_RATIO = ("U18 POPULATION TOT NON-FAMILY HOUSEHOLDS" * 1.0 / "U18 POPULATION IN TOTAL");

SELECT * FROM family_status