select * from hl_population;

ALTER TABLE hl_population
ADD COLUMN POPULATION_WHITE_RATIO numeric;

ALTER TABLE hl_population
ADD COLUMN POPULATION_BLACK_AA_RATIO numeric;

ALTER TABLE hl_population
ADD COLUMN POPULATION_INDIGENOUS_RATIO numeric;

ALTER TABLE hl_population
ADD COLUMN POPULATION_ASIAN_RATIO numeric;

ALTER TABLE hl_population
ADD COLUMN POPULATION_HAW_PAC_ISLANDER_RATIO numeric;

ALTER TABLE hl_population
ADD COLUMN POPULATION_OTHER_RATIO numeric;

ALTER TABLE hl_population
ADD COLUMN POPULATION_MIXED_RATIO numeric;

ALTER TABLE hl_population
ADD COLUMN POPULATION_HISPANIC_LATINO_RATIO numeric;


DELETE FROM hl_population WHERE "POPULATION_TOTAL" = 0;

UPDATE hl_population set POPULATION_WHITE_RATIO = ("POPULATION NH WHITE" * 1.0 / "POPULATION_TOTAL");
UPDATE hl_population set POPULATION_BLACK_AA_RATIO = ("POPULATION NH BLACK/AA" * 1.0 / "POPULATION_TOTAL");
UPDATE hl_population set POPULATION_INDIGENOUS_RATIO = ("POPULATION NH INDIGENOUS" * 1.0 / "POPULATION_TOTAL");
UPDATE hl_population set POPULATION_ASIAN_RATIO = ("NH ASIAN" * 1.0 / "POPULATION_TOTAL");
UPDATE hl_population set POPULATION_HAW_PAC_ISLANDER_RATIO = ("POPULATION NH HAW/PAC ISLANDER" * 1.0 / "POPULATION_TOTAL");
UPDATE hl_population set POPULATION_OTHER_RATIO = ("POPULATION OTHER RACE" * 1.0 / "POPULATION_TOTAL");
UPDATE hl_population set POPULATION_MIXED_RATIO = ("NH MIXED RACES" * 1.0 / "POPULATION_TOTAL");
UPDATE hl_population set POPULATION_HISPANIC_LATINO_RATIO = ("POPULATION HISPANIC/LATINO" * 1.0 / "POPULATION_TOTAL");

SELECT * FROM hl_population